spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ht.allhere.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: true
  identity: MYSQL
  style: camelhump
  use-java-type: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql